### ISSUE TITLE
Can not find 'uk.ac.cam.ch.wwmm.chemicaltagger.pregenerated.ChemicalChunkerParser'

### ISSUE THREAD

**Issue by tongyey** [BlueObelisk/chemicaltagger#12]
When I run the code, an error is reported as: can not find 'uk.ac.cam.ch.wwmm.chemicaltagger.pregenerated‘. May I know how to solve it? Thank you.

**Comment by mjw99** [comment]
Can you explicitly list the steps you took to generate the error, so that I can attempt to reproduce the issue?
