### ISSUE TITLE
RecombineTokens bug

### ISSUE THREAD

**Issue by lo2aayy** [BlueObelisk/chemicaltagger#3]
In the method RecombineTokens if there are more than 2 "dash" tags after each other they will be repeated as the indexList adds the current and next, and then afterwards they're added again.

Example:

Input: N(C/-/-3)
will be tokenized to: [ "N(C/-//-3" , ")" ]

an if condition to check if it exists before adding an index to the indexList will resolve it.

**Comment by mjw99** [comment]
Try submitting a PR to see if the suggestion passed the current test suite.
