### ISSUE TITLE
Can't find uk.ac.cam.ch.wwmm.chemicaltagger.pregenerated

### ISSUE THREAD

**Issue by CreamyLong** [BlueObelisk/chemicaltagger#9]
when I run the demo code, the error is that the program cannot find the "pregenerated" file.  I do not find it in the repo as well.
Could you help me?

**Comment by mjw99** [comment]
Have you built it correctly?
```bash
mvn clean install
```

**Comment by CreamyLong** [comment]
Thanks. I reinstall the mvn and it works now
